language: node_js
node_js:
  - node
script:
  - npm test

deploy:
  provider: heroku
  api_key:
    secure: 5276ba1b-ee72-4aa4-a1d4-79ca1ca959be
  app: evening-coast-40943
  on:
    repo: alexfilatov2000/mongooseL
